on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-and-push-teachers-image:
    strategy:
      fail-fast: false
      matrix:
        include:
          - node-version: "node:16-alpine3.15@sha256:a2c7f8ebdec79619fba306cec38150db44a45b48380d09603d3602139c5a5f92"
            node-version-string: 'nodejs-16'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker build
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Log in to github registry
        run:  |
          echo "${{ secrets.GITHUB_TOKEN }}" |
          docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: Dockerfile
          pull: true
          push: true
          tags: |
            ghcr.io/so-gineers/workbook-students:1.0.0-node-${{ matrix.node-version-string }}
          build-args: |
            NODE_VERSION=${{ matrix.node-version }}